require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'QRReaderExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])



  target 'QRReaderExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end

  pod 'React', :path => '../node_modules/react-native'

  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'


  # React-Native is not great about React double-including from the Podfile
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      if target.name == "React"
        target.remove_from_project
      end

      # It removes React & Yoga from the Pods project, as it is already included in the main project.
      targets_to_ignore = %w(React yoga)
      if targets_to_ignore.include? target.name
        target.remove_from_project
      end
    end
  end
end

target 'QRReaderExample-tvOS' do
  # Pods for QRReaderExample-tvOS

  target 'QRReaderExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
